<?php

use Illuminate\Database\Seeder;
use App\Region;
class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public $reg = array(
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Zlatoust','country' => 'Россия','region' => 'Челябинская область','city' => 'Златоуст','lat' => '55.1558787','lng' => '59.6858853'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Kazan','country' => 'Россия','region' => 'Татарстан','city' => 'Казань','lat' => '55.1558787','lng' => '59.6858853'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Zhukovskiy','country' => 'Россия','region' => 'Московская область','city' => 'Жуковский','lat' => '55.5974912','lng' => '38.1132562'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Zhigulevsk','country' => 'Россия','region' => 'Самарская область','city' => 'Жигулевск','lat' => '53.3907252','lng' => '49.4722695'),
        array('country_en' => 'Russia','region_en' => 'Kursk','city_en' => 'Zheleznogorsk','country' => 'Россия','region' => 'Курская область','city' => 'Железногорск','lat' => '52.3332892','lng' => '35.3669551'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Zheleznodorozhnyy','country' => 'Россия','region' => 'Московская область','city' => 'Железнодорожный','lat' => '55.7373757','lng' => '38.0095391'),
        array('country_en' => 'Russia','region_en' => 'Moscow','city_en' => 'Zelenograd','country' => 'Россия','region' => 'город Москва','city' => 'Зеленоград','lat' => '55.9871526','lng' => '37.2021514'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Zelenodolsk','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Зеленодольск','lat' => '55.8516037','lng' => '48.5371529'),
        array('country_en' => 'Russia','region_en' => 'Penza','city_en' => 'Zarechnyy','country' => 'Россия','region' => 'Пензенская область','city' => 'Заречный','lat' => '53.1855799','lng' => '45.1685087'),
        array('country_en' => 'Russia','region_en' => 'Mariy-El','city_en' => 'Yoshkar-Ola','country' => 'Россия','region' => 'Республика Марий Эл','city' => 'Йошкар-Ола','lat' => '56.6402225','lng' => '47.883858'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Yeysk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Ейск','lat' => '46.6825784','lng' => '38.2702941'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Yessentuki','country' => 'Россия','region' => 'Ставропольский край','city' => 'Ессентуки','lat' => '44.0455121','lng' => '42.8575232'),
        array('country_en' => 'Russia','region_en' => 'Lipetsk','city_en' => 'Yelets','country' => 'Россия','region' => 'Липецкая область','city' => 'Елец','lat' => '52.6170992','lng' => '38.5048669'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Yelabuga','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Елабуга','lat' => '55.763166','lng' => '52.0254936'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Yegor\'yevsk','country' => 'Россия','region' => 'Московская область','city' => 'Егорьевск','lat' => '55.3851413','lng' => '39.0323223'),
        array('country_en' => 'Russia','region_en' => 'Smolensk','city_en' => 'Yartsevo','country' => 'Россия','region' => 'Смоленская область','city' => 'Ярцево','lat' => '55.0592988','lng' => '32.6850128'),
        array('country_en' => 'Russia','region_en' => 'Jaroslavl','city_en' => 'Yaroslavl','country' => 'Россия','region' => 'Ярославская область','city' => 'Ярославль','lat' => '57.6260744','lng' => '39.8844708'),
        array('country_en' => 'Russia','region_en' => 'Tverskaya','city_en' => 'Vyshniy Volochek','country' => 'Россия','region' => 'Тверская область','city' => 'Вышний Волочёк','lat' => '57.5836032','lng' => '34.5642592'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Vyksa','country' => 'Россия','region' => 'Нижегородская область','city' => 'Выкса','lat' => '55.3262146','lng' => '42.17017'),
        array('country_en' => 'Russia','region_en' => 'Leningrad','city_en' => 'Vyborg','country' => 'Россия','region' => 'Ленинградская область','city' => 'Выборг','lat' => '60.7139529','lng' => '28.7571571'),
        array('country_en' => 'Russia','region_en' => 'Smolensk','city_en' => 'Vyaz\'ma','country' => 'Россия','region' => 'Смоленская область','city' => 'Вязьма','lat' => '55.1929028','lng' => '34.2966705'),
        array('country_en' => 'Russia','region_en' => 'Udmurtiya','city_en' => 'Votkinsk','country' => 'Россия','region' => 'республика Удмуртия','city' => 'Воткинск','lat' => '57.0409442','lng' => '53.9769303'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Voskresensk','country' => 'Россия','region' => 'Московская область','city' => 'Воскресенск','lat' => '55.3238424','lng' => '38.6815131'),
        array('country_en' => 'Russia','region_en' => 'Voronezj','city_en' => 'Voronezh','country' => 'Россия','region' => 'Воронежская область','city' => 'Воронеж','lat' => '51.6754966','lng' => '39.2088823'),
        array('country_en' => 'Russia','region_en' => 'Volgograd','city_en' => 'Volzhskiy','country' => 'Россия','region' => 'Волгоградская область','city' => 'Волжский','lat' => '48.8176494','lng' => '44.7707294'),
        array('country_en' => 'Russia','region_en' => 'Mariy-El','city_en' => 'Volzhsk','country' => 'Россия','region' => 'Республика Марий Эл','city' => 'Волжск','lat' => '55.8722768','lng' => '48.3568519'),
        array('country_en' => 'Russia','region_en' => 'Saratov','city_en' => 'Vol\'sk','country' => 'Россия','region' => 'Саратовская область','city' => 'Вольск','lat' => '52.0497081','lng' => '47.3692266'),
        array('country_en' => 'Russia','region_en' => 'Vologda','city_en' => 'Vologda','country' => 'Россия','region' => 'Вологодская область','city' => 'Вологда','lat' => '59.2180665','lng' => '39.8978052'),
        array('country_en' => 'Russia','region_en' => 'Volgograd','city_en' => 'Volgograd','country' => 'Россия','region' => 'Волгоградская область','city' => 'Волгоград','lat' => '48.708048','lng' => '44.5133034'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Volgodonsk','country' => 'Россия','region' => 'Ростовская область','city' => 'Волгодонск','lat' => '47.5060474','lng' => '42.1794336'),
        array('country_en' => 'Russia','region_en' => 'Vladimir','city_en' => 'Vladimir','country' => 'Россия','region' => 'Владимирская область','city' => 'Владимир','lat' => '56.1445956','lng' => '40.4178686'),
        array('country_en' => 'Russia','region_en' => 'North Ossetia','city_en' => 'Vladikavkaz','country' => 'Россия','region' => 'Республика Северная Осетия-Алания','city' => 'Владикавказ','lat' => '43.0252344','lng' => '44.6659759'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Vidnoye','country' => 'Россия','region' => 'Московская область','city' => 'Видное','lat' => '55.5470892','lng' => '37.6986011'),
        array('country_en' => 'Russia','region_en' => 'Pskov','city_en' => 'Velikiye Luki','country' => 'Россия','region' => 'Псковская область','city' => 'Великие Луки','lat' => '56.3396088','lng' => '30.5314751'),
        array('country_en' => 'Russia','region_en' => 'Tula','city_en' => 'Uzlovaya','country' => 'Россия','region' => 'Тульская область','city' => 'Узловая','lat' => '53.9822632','lng' => '38.177094'),
        array('country_en' => 'Russia','region_en' => 'Ulyanovsk','city_en' => 'Ulyanovsk','country' => 'Россия','region' => 'Ульяновская область','city' => 'Ульяновск','lat' => '54.3181598','lng' => '48.3837914'),
        array('country_en' => 'Russia','region_en' => 'Komi Republic','city_en' => 'Ukhta','country' => 'Россия','region' => 'Республика Коми','city' => 'Ухта','lat' => '63.567321','lng' => '53.7471594'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Ufa','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Уфа','lat' => '54.7387621','lng' => '55.9720554'),
        array('country_en' => 'Russia','region_en' => 'Tverskaya','city_en' => 'Tver','country' => 'Россия','region' => 'Тверская область','city' => 'Тверь','lat' => '56.8587214','lng' => '35.9175965'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Tuymazy','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Туймазы','lat' => '54.598534','lng' => '53.6921837'),
        array('country_en' => 'Russia','region_en' => 'Tula','city_en' => 'Tula','country' => 'Россия','region' => 'Тульская область','city' => 'Тула','lat' => '54.204836','lng' => '37.6184915'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Tuapse','country' => 'Россия','region' => 'Краснодарский край','city' => 'Туапсе','lat' => '44.106518','lng' => '39.0806454'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Tol\'yatti','country' => 'Россия','region' => 'Самарская область','city' => 'Тольятти','lat' => '53.5086002','lng' => '49.4198344'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Timashevsk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Тимашевск','lat' => '45.6093387','lng' => '38.9547015'),
        array('country_en' => 'Russia','region_en' => 'Leningrad','city_en' => 'Tikhvin','country' => 'Россия','region' => 'Ленинградская область','city' => 'Тихвин','lat' => '59.6443858','lng' => '33.541032'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Tikhoretsk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Тихорецк','lat' => '45.8676515','lng' => '40.1050949'),
        array('country_en' => 'Russia','region_en' => 'Tambov','city_en' => 'Tambov','country' => 'Россия','region' => 'Тамбовская область','city' => 'Тамбов','lat' => '52.723598','lng' => '41.4423062'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Taganrog','country' => 'Россия','region' => 'Ростовская область','city' => 'Таганрог','lat' => '47.2416334','lng' => '38.8676013'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Syzran\'','country' => 'Россия','region' => 'Самарская область','city' => 'Сызрань','lat' => '53.1504504','lng' => '48.397896'),
        array('country_en' => 'Russia','region_en' => 'Komi Republic','city_en' => 'Syktyvkar','country' => 'Россия','region' => 'Республика Коми','city' => 'Сыктывкар','lat' => '61.6478508','lng' => '50.8339029'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Stupino','country' => 'Россия','region' => 'Московская область','city' => 'Ступино','lat' => '54.9040441','lng' => '38.0803509'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Sterlitamak','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Стерлитамак','lat' => '53.6554353','lng' => '55.9438932'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Stavropol\'','country' => 'Россия','region' => 'Ставропольский край','city' => 'Ставрополь','lat' => '45.0454764','lng' => '41.9683431'),
        array('country_en' => 'Russia','region_en' => 'Belgorod','city_en' => 'Staryy Oskol','country' => 'Россия','region' => 'Белгородская область','city' => 'Старый Оскол','lat' => '51.2980824','lng' => '37.8379593'),
        array('country_en' => 'Russia','region_en' => 'Leningrad','city_en' => 'Sosnovyy Bor','country' => 'Россия','region' => 'Ленинградская область','city' => 'Сосновый Бор','lat' => '59.8696729','lng' => '29.0856478'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Solnechnogorsk','country' => 'Россия','region' => 'Московская область','city' => 'Солнечногорск','lat' => '56.1852039','lng' => '36.9776171'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Solikamsk','country' => 'Россия','region' => 'Пермский край','city' => 'Соликамск','lat' => '59.6720331','lng' => '56.7557668'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Sochi','country' => 'Россия','region' => 'Краснодарский край','city' => 'Сочи','lat' => '43.6028079','lng' => '39.7341543'),
        array('country_en' => 'Russia','region_en' => 'Smolensk','city_en' => 'Smolensk','country' => 'Россия','region' => 'Смоленская область','city' => 'Смоленск','lat' => '54.7903112','lng' => '32.0503663'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Slavyansk-na-Kubani','country' => 'Россия','region' => 'Краснодарский край','city' => 'Славянск-на-Кубани','lat' => '45.2455578','lng' => '38.140311'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Sibay','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Сибай','lat' => '52.7133586','lng' => '58.6681358'),
        array('country_en' => 'Russia','region_en' => 'Ivanovo','city_en' => 'Shuya','country' => 'Россия','region' => 'Ивановская область','city' => 'Шуя','lat' => '56.8511341','lng' => '41.357534'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Mikhaylovsk','country' => 'Россия','region' => 'Ставропольский край','city' => 'Михайловск','lat' => '45.128744','lng' => '42.0092318'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Shchelkovo','country' => 'Россия','region' => 'Московская область','city' => 'Щелково','lat' => '55.917038','lng' => '38.0369347'),
        array('country_en' => 'Russia','region_en' => 'Tula','city_en' => 'Shchekino','country' => 'Россия','region' => 'Тульская область','city' => 'Щекино','lat' => '54.0009718','lng' => '37.5203722'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Shakhty','country' => 'Россия','region' => 'Ростовская область','city' => 'Шахты','lat' => '47.7236224','lng' => '40.2355138'),
        array('country_en' => 'Russia','region_en' => 'Murmansk','city_en' => 'Severomorsk','country' => 'Россия','region' => 'Мурманская область','city' => 'Североморск','lat' => '69.0655058','lng' => '33.4092689'),
        array('country_en' => 'Russia','region_en' => 'Arkhangelskaya','city_en' => 'Severodvinsk','country' => 'Россия','region' => 'Архангельская область','city' => 'Северодвинск','lat' => '64.5661757','lng' => '39.8505981'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Serpukhov','country' => 'Россия','region' => 'Московская область','city' => 'Серпухов','lat' => '54.9179562','lng' => '37.4229963'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Sergiyev Posad','country' => 'Россия','region' => 'Московская область','city' => 'Сергиев Посад','lat' => '56.3242317','lng' => '38.1452115'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Sarov','country' => 'Россия','region' => 'Нижегородская область','city' => 'Саров','lat' => '54.9342792','lng' => '43.3252503'),
        array('country_en' => 'Russia','region_en' => 'Saratov','city_en' => 'Saratov','country' => 'Россия','region' => 'Саратовская область','city' => 'Саратов','lat' => '51.5563789','lng' => '45.9798167'),
        array('country_en' => 'Russia','region_en' => 'Udmurtiya','city_en' => 'Sarapul','country' => 'Россия','region' => 'республика Удмуртия','city' => 'Сарапул','lat' => '56.4539288','lng' => '53.7742185'),
        array('country_en' => 'Russia','region_en' => 'Mordoviya','city_en' => 'Saransk','country' => 'Россия','region' => 'Республика Мордовия','city' => 'Саранск','lat' => '54.2000477','lng' => '45.1745115'),
        array('country_en' => 'Russia','region_en' => 'St.-Petersburg','city_en' => 'Saint Petersburg','country' => 'Россия','region' => 'город Санкт-Петербург','city' => 'Санкт-Петербург','lat' => '59.9342802','lng' => '30.3350986'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Samara','country' => 'Россия','region' => 'Самарская область','city' => 'Самара','lat' => '53.2415041','lng' => '50.2212463'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Sal\'sk','country' => 'Россия','region' => 'Ростовская область','city' => 'Сальск','lat' => '46.4769159','lng' => '41.5288014'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Salavat','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Салават','lat' => '53.3860437','lng' => '55.9259472'),
        array('country_en' => 'Russia','region_en' => 'Tverskaya','city_en' => 'Rzhev','country' => 'Россия','region' => 'Тверская область','city' => 'Ржев','lat' => '56.2583967','lng' => '34.3283487'),
        array('country_en' => 'Russia','region_en' => 'Jaroslavl','city_en' => 'Rybinsk','country' => 'Россия','region' => 'Ярославская область','city' => 'Рыбинск','lat' => '58.057486','lng' => '38.8116968'),
        array('country_en' => 'Russia','region_en' => 'Rjazan','city_en' => 'Ryazan\'','country' => 'Россия','region' => 'Рязанская область','city' => 'Рязань','lat' => '54.6095418','lng' => '39.7125857'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Rostov-na-Donu','country' => 'Россия','region' => 'Ростовская область','city' => 'Ростов-на-Дону','lat' => '47.2357137','lng' => '39.701505'),
        array('country_en' => 'Russia','region_en' => 'Voronezj','city_en' => 'Rossosh\'','country' => 'Россия','region' => 'Воронежская область','city' => 'Россошь','lat' => '50.1943409','lng' => '39.5784111'),
        array('country_en' => 'Russia','region_en' => 'Smolensk','city_en' => 'Roslavl\'','country' => 'Россия','region' => 'Смоленская область','city' => 'Рославль','lat' => '53.953118','lng' => '32.863845'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Revda','country' => 'Россия','region' => 'Свердловская область','city' => 'Ревда','lat' => '56.8188497','lng' => '59.9036396'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Reutov','country' => 'Россия','region' => 'Московская область','city' => 'Реутов','lat' => '55.7617579','lng' => '37.8613023'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Pyatigorsk','country' => 'Россия','region' => 'Ставропольский край','city' => 'Пятигорск','lat' => '44.0498933','lng' => '43.039636'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Pushkino','country' => 'Россия','region' => 'Московская область','city' => 'Пушкино','lat' => '55.987833','lng' => '37.8411773'),
        array('country_en' => 'Russia','region_en' => 'St.-Petersburg','city_en' => 'Pushkin','country' => 'Россия','region' => 'город Санкт-Петербург','city' => 'Пушкин','lat' => '59.717593','lng' => '30.4060041'),
        array('country_en' => 'Russia','region_en' => 'Pskov','city_en' => 'Pskov','country' => 'Россия','region' => 'Псковская область','city' => 'Псков','lat' => '57.8166994','lng' => '28.3344734'),
        array('country_en' => 'Russia','region_en' => 'Kabardino-Balkariya','city_en' => 'Prokhladnyy','country' => 'Россия','region' => 'Кабардино-Балкарская Республика','city' => 'Прохладный','lat' => '43.7545901','lng' => '44.0263743'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Podol\'sk','country' => 'Россия','region' => 'Московская область','city' => 'Подольск','lat' => '55.4312453','lng' => '37.5457647'),
        array('country_en' => 'Russia','region_en' => 'Republic of Karelia','city_en' => 'Petrozavodsk','country' => 'Россия','region' => 'Республика Карелия','city' => 'Петрозаводск','lat' => '61.7781617','lng' => '34.3640396'),
        array('country_en' => 'Russia','region_en' => 'St.-Petersburg','city_en' => 'Peterhof','country' => 'Россия','region' => 'город Санкт-Петербург','city' => 'Петергоф','lat' => '59.8845003','lng' => '29.8851756'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Pervoural\'sk','country' => 'Россия','region' => 'Свердловская область','city' => 'Первоуральск','lat' => '56.8999158','lng' => '59.9521128'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Perm','country' => 'Россия','region' => 'Пермский край','city' => 'Пермь','lat' => '58.0296813','lng' => '56.2667916'),
        array('country_en' => 'Russia','region_en' => 'Moscow','city_en' => 'Novo-Peredelkino','country' => 'Россия','region' => 'город Москва','city' => 'район Ново-Переделкино','lat' => '55.6439071','lng' => '37.355717'),
        array('country_en' => 'Russia','region_en' => 'Penza','city_en' => 'Penza','country' => 'Россия','region' => 'Пензенская область','city' => 'Пенза','lat' => '53.2272903','lng' => '45'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Pavlovskiy Posad','country' => 'Россия','region' => 'Московская область','city' => 'Павловский Посад','lat' => '55.7758031','lng' => '38.6532915'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Otradnyy','country' => 'Россия','region' => 'Самарская область','city' => 'Отрадный','lat' => '53.3762199','lng' => '51.3344572'),
        array('country_en' => 'Russia','region_en' => 'Orenburg','city_en' => 'Orsk','country' => 'Россия','region' => 'Оренбургская область','city' => 'Орск','lat' => '51.2145242','lng' => '58.5440566'),
        array('country_en' => 'Russia','region_en' => 'Orenburg','city_en' => 'Orenburg','country' => 'Россия','region' => 'Оренбургская область','city' => 'Оренбург','lat' => '51.7666482','lng' => '55.1004538'),
        array('country_en' => 'Russia','region_en' => 'Orjol','city_en' => 'Orel','country' => 'Россия','region' => 'Орловская область','city' => 'Орёл','lat' => '52.9668468','lng' => '36.0624898'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Orekhovo-Zuyevo','country' => 'Россия','region' => 'Московская область','city' => 'Орехово-Зуево','lat' => '55.8034354','lng' => '38.9667902'),
        array('country_en' => 'Russia','region_en' => 'Ingushetiya','city_en' => 'Ordzhonikidzevskaya','country' => 'Россия','region' => 'Республика Ингушетия','city' => 'Орджоникидзевская','lat' => '43.3213308','lng' => '45.044839'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Oktyabr\'skiy','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Октябрьский','lat' => '54.4772015','lng' => '53.4895394'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Odintsovo','country' => 'Россия','region' => 'Московская область','city' => 'Одинцово','lat' => '55.6733745','lng' => '37.2818569'),
        array('country_en' => 'Russia','region_en' => 'Kaluga','city_en' => 'Obninsk','country' => 'Россия','region' => 'Калужская область','city' => 'Обнинск','lat' => '55.1170375','lng' => '36.5970818'),
        array('country_en' => 'Russia','region_en' => 'Orenburg','city_en' => 'Novotroitsk','country' => 'Россия','region' => 'Оренбургская область','city' => 'Новотроицк','lat' => '51.2096144','lng' => '58.314662'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Novoshakhtinsk','country' => 'Россия','region' => 'Ростовская область','city' => 'Новошахтинск','lat' => '47.7560583','lng' => '39.9341063'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Novorossiysk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Новороссийск','lat' => '44.7154014','lng' => '37.7619669'),
        array('country_en' => 'Russia','region_en' => 'Tula','city_en' => 'Novomoskovsk','country' => 'Россия','region' => 'Тульская область','city' => 'Новомосковск','lat' => '54.0109034','lng' => '38.2963063'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Novokuybyshevsk','country' => 'Россия','region' => 'Самарская область','city' => 'Новокуйбышевск','lat' => '53.0960666','lng' => '49.8912888'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Novocherkassk','country' => 'Россия','region' => 'Ростовская область','city' => 'Новочеркасск','lat' => '47.4177687','lng' => '40.0726784'),
        array('country_en' => 'Russia','region_en' => 'Chuvashia','city_en' => 'Novocheboksarsk','country' => 'Россия','region' => 'Чувашская Республика','city' => 'Новочебоксарск','lat' => '56.103603','lng' => '47.5065073'),
        array('country_en' => 'Russia','region_en' => 'Novgorod','city_en' => 'Velikiy Novgorod','country' => 'Россия','region' => 'Новгородская область','city' => 'Великий Новгород','lat' => '58.5255698','lng' => '31.2741928'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Noginsk','country' => 'Россия','region' => 'Московская область','city' => 'Ногинск','lat' => '55.8761163','lng' => '38.4666594'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Nizhniy Tagil','country' => 'Россия','region' => 'Свердловская область','city' => 'Нижний Тагил','lat' => '57.9214912','lng' => '59.9816186'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Nizhniy Novgorod','country' => 'Россия','region' => 'Нижегородская область','city' => 'Нижний Новгород','lat' => '56.2965039','lng' => '43.9360589'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Nizhnekamsk','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Нижнекамск','lat' => '55.613196','lng' => '51.8469974'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Nevinnomyssk','country' => 'Россия','region' => 'Ставропольский край','city' => 'Невинномысск','lat' => '44.638015','lng' => '41.9504639'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Neftekamsk','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Нефтекамск','lat' => '56.1026081','lng' => '54.2867394'),
        array('country_en' => 'Russia','region_en' => 'Ingushetiya','city_en' => 'Nazran\'','country' => 'Россия','region' => 'Республика Ингушетия','city' => 'Назрань','lat' => '43.2148801','lng' => '44.7763501'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Naro-Fominsk','country' => 'Россия','region' => 'Московская область','city' => 'Наро-Фоминск','lat' => '55.3916241','lng' => '36.7249432'),
        array('country_en' => 'Russia','region_en' => 'Kabardino-Balkariya','city_en' => 'Nal\'chik','country' => 'Россия','region' => 'Кабардино-Балкарская Республика','city' => 'Нальчик','lat' => '43.4949918','lng' => '43.6045132'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Naberezhnyye Chelny','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Набережные Челны','lat' => '55.7185054','lng' => '52.3721038'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Mytishchi','country' => 'Россия','region' => 'Московская область','city' => 'Мытищи','lat' => '55.9198471','lng' => '37.7654985'),
        array('country_en' => 'Russia','region_en' => 'Vladimir','city_en' => 'Murom','country' => 'Россия','region' => 'Владимирская область','city' => 'Муром','lat' => '55.5673975','lng' => '42.0165852'),
        array('country_en' => 'Russia','region_en' => 'Murmansk','city_en' => 'Murmansk','country' => 'Россия','region' => 'Мурманская область','city' => 'Мурманск','lat' => '68.9585244','lng' => '33.0826598'),
        array('country_en' => 'Russia','region_en' => 'Moscow','city_en' => 'Moscow','country' => 'Россия','region' => 'город Москва','city' => 'Москва','lat' => '55.755826','lng' => '37.6173'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Mineralnye Vody','country' => 'Россия','region' => 'Ставропольский край','city' => 'Минеральные Воды','lat' => '44.211675','lng' => '43.1238527'),
        array('country_en' => 'Russia','region_en' => 'Volgograd','city_en' => 'Mikhaylovka','country' => 'Россия','region' => 'Волгоградская область','city' => 'Михайловка','lat' => '50.064793','lng' => '43.2284277'),
        array('country_en' => 'Russia','region_en' => 'Tambov','city_en' => 'Michurinsk','country' => 'Россия','region' => 'Тамбовская область','city' => 'Мичуринск','lat' => '52.8930342','lng' => '40.4980963'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Meleuz','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Мелеуз','lat' => '52.9622477','lng' => '55.9358645'),
        array('country_en' => 'Russia','region_en' => 'Adygeya','city_en' => 'Maykop','country' => 'Россия','region' => 'Республика Адыгея','city' => 'Майкоп','lat' => '44.5984115','lng' => '40.1080869'),
        array('country_en' => 'Russia','region_en' => 'Dagestan','city_en' => 'Makhachkala','country' => 'Россия','region' => 'Республика Дагестан','city' => 'Махачкала','lat' => '42.9666308','lng' => '47.5126285'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Magnitogorsk','country' => 'Россия','region' => 'Челябинская область','city' => 'Магнитогорск','lat' => '53.4129429','lng' => '59.0016233'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Lyubertsy','country' => 'Россия','region' => 'Московская область','city' => 'Люберцы','lat' => '55.686462','lng' => '37.8981554'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Lytkarino','country' => 'Россия','region' => 'Московская область','city' => 'Лыткарино','lat' => '55.579537','lng' => '37.9120395'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Lys\'va','country' => 'Россия','region' => 'Пермский край','city' => 'Лысьва','lat' => '58.1072052','lng' => '57.7888508'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Lobnya','country' => 'Россия','region' => 'Московская область','city' => 'Лобня','lat' => '56.0172312','lng' => '37.4852637'),
        array('country_en' => 'Russia','region_en' => 'Orjol','city_en' => 'Livny','country' => 'Россия','region' => 'Орловская область','city' => 'Ливны','lat' => '52.424625','lng' => '37.5996415'),
        array('country_en' => 'Russia','region_en' => 'Voronezj','city_en' => 'Liski','country' => 'Россия','region' => 'Воронежская область','city' => 'Лиски','lat' => '50.979677','lng' => '39.4941294'),
        array('country_en' => 'Russia','region_en' => 'Lipetsk','city_en' => 'Lipetsk','country' => 'Россия','region' => 'Липецкая область','city' => 'Липецк','lat' => '52.6121996','lng' => '39.5981225'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Leninogorsk','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Лениногорск','lat' => '54.6013024','lng' => '52.4607127'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Labinsk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Лабинск','lat' => '44.6323416','lng' => '40.738855'),
        array('country_en' => 'Russia','region_en' => 'Penza','city_en' => 'Kuznetsk','country' => 'Россия','region' => 'Пензенская область','city' => 'Кузнецк','lat' => '53.1183655','lng' => '46.5845515'),
        array('country_en' => 'Russia','region_en' => 'Kursk','city_en' => 'Kursk','country' => 'Россия','region' => 'Курская область','city' => 'Курск','lat' => '51.7091957','lng' => '36.1562241'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Kungur','country' => 'Россия','region' => 'Пермский край','city' => 'Кунгур','lat' => '57.4115048','lng' => '56.9916948'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Kumertau','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Кумертау','lat' => '52.7637387','lng' => '55.8115682'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Kstovo','country' => 'Россия','region' => 'Нижегородская область','city' => 'Кстово','lat' => '56.1328851','lng' => '44.1740097'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Krymsk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Крымск','lat' => '44.9277854','lng' => '37.9932125'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Kropotkin','country' => 'Россия','region' => 'Краснодарский край','city' => 'Кропоткин','lat' => '45.4296049','lng' => '40.5540351'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Krasnokamsk','country' => 'Россия','region' => 'Пермский край','city' => 'Краснокамск','lat' => '58.0789548','lng' => '55.7671866'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Krasnogorsk','country' => 'Россия','region' => 'Московская область','city' => 'Красногорск','lat' => '55.8263313','lng' => '37.326297'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Krasnodar','country' => 'Россия','region' => 'Краснодарский край','city' => 'Краснодар','lat' => '45.0392674','lng' => '38.987221'),
        array('country_en' => 'Russia','region_en' => 'Vladimir','city_en' => 'Kovrov','country' => 'Россия','region' => 'Владимирская область','city' => 'Ковров','lat' => '56.356769','lng' => '41.3226311'),
        array('country_en' => 'Russia','region_en' => 'Arkhangelskaya','city_en' => 'Kotlas','country' => 'Россия','region' => 'Архангельская область','city' => 'Котлас','lat' => '61.2468493','lng' => '46.6618007'),
        array('country_en' => 'Russia','region_en' => 'Kostroma','city_en' => 'Kostroma','country' => 'Россия','region' => 'Костромская область','city' => 'Кострома','lat' => '57.7774816','lng' => '40.9698928'),
        array('country_en' => 'Russia','region_en' => 'St.-Petersburg','city_en' => 'Kolpino','country' => 'Россия','region' => 'город Санкт-Петербург','city' => 'Колпино','lat' => '59.761761','lng' => '30.5788969'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Kolomna','country' => 'Россия','region' => 'Московская область','city' => 'Коломна','lat' => '55.0937517','lng' => '38.7688618'),
        array('country_en' => 'Russia','region_en' => 'Brjansk','city_en' => 'Klintsy','country' => 'Россия','region' => 'Брянская область','city' => 'Клинцы','lat' => '52.7566164','lng' => '32.2566693'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Klin','country' => 'Россия','region' => 'Московская область','city' => 'Клин','lat' => '56.3333816','lng' => '36.730447'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Klimovsk','country' => 'Россия','region' => 'Московская область','city' => 'Климовск','lat' => '55.359093','lng' => '37.5210415'),
        array('country_en' => 'Russia','region_en' => 'Dagestan','city_en' => 'Kizlyar','country' => 'Россия','region' => 'Республика Дагестан','city' => 'Кизляр','lat' => '43.8451098','lng' => '46.7016441'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Kislovodsk','country' => 'Россия','region' => 'Ставропольский край','city' => 'Кисловодск','lat' => '43.9056014','lng' => '42.7280949'),
        array('country_en' => 'Russia','region_en' => 'Kirov','city_en' => 'Kirovo-Chepetsk','country' => 'Россия','region' => 'Кировская область','city' => 'Кирово-Чепецк','lat' => '58.5540671','lng' => '49.9885606'),
        array('country_en' => 'Russia','region_en' => 'Kirov','city_en' => 'Kirov','country' => 'Россия','region' => 'Кировская область','city' => 'Киров','lat' => '58.6035321','lng' => '49.6667983'),
        array('country_en' => 'Russia','region_en' => 'Leningrad','city_en' => 'Kirishi','country' => 'Россия','region' => 'Ленинградская область','city' => 'Кириши','lat' => '59.4460543','lng' => '32.015188'),
        array('country_en' => 'Russia','region_en' => 'Leningrad','city_en' => 'Kingisepp','country' => 'Россия','region' => 'Ленинградская область','city' => 'Кингисепп','lat' => '59.3759603','lng' => '28.6043387'),
        array('country_en' => 'Russia','region_en' => 'Ivanovo','city_en' => 'Kineshma','country' => 'Россия','region' => 'Ивановская область','city' => 'Кинешма','lat' => '57.4426249','lng' => '42.1159511'),
        array('country_en' => 'Russia','region_en' => 'Tverskaya','city_en' => 'Kimry','country' => 'Россия','region' => 'Тверская область','city' => 'Кимры','lat' => '56.8603977','lng' => '37.3598916'),
        array('country_en' => 'Russia','region_en' => 'Moscow','city_en' => 'Khimki','country' => 'Россия','region' => 'Московская область','city' => 'Химки','lat' => '55.8940553','lng' => '37.4439487'),
        array('country_en' => 'Russia','region_en' => 'Dagestan','city_en' => 'Khasavyurt','country' => 'Россия','region' => 'Республика Дагестан','city' => 'Хасавюрт','lat' => '43.2562013','lng' => '46.5893353'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Kazan','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Казань','lat' => '55.8304307','lng' => '49.0660806'),
        array('country_en' => 'Russia','region_en' => 'Dagestan','city_en' => 'Kaspiysk','country' => 'Россия','region' => 'Республика Дагестан','city' => 'Каспийск','lat' => '42.8740492','lng' => '47.6404175'),
        array('country_en' => 'Russia','region_en' => 'Volgograd','city_en' => 'Kamyshin','country' => 'Россия','region' => 'Волгоградская область','city' => 'Камышин','lat' => '50.0946344','lng' => '45.3939821'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Kamensk-Shakhtinskiy','country' => 'Россия','region' => 'Ростовская область','city' => 'Каменск-Шахтинский','lat' => '48.310299','lng' => '40.2445448'),
        array('country_en' => 'Russia','region_en' => 'Kaluga','city_en' => 'Kaluga','country' => 'Россия','region' => 'Калужская область','city' => 'Калуга','lat' => '54.5518584','lng' => '36.2850973'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Korolev','country' => 'Россия','region' => 'Московская область','city' => 'Королев','lat' => '55.9316797','lng' => '37.8518552'),
        array('country_en' => 'Russia','region_en' => 'Kaliningrad','city_en' => 'Kaliningrad','country' => 'Россия','region' => 'Калининградская область','city' => 'Калининград','lat' => '54.7104264','lng' => '20.4522144'),
        array('country_en' => 'Russia','region_en' => 'Udmurtiya','city_en' => 'Izhevsk','country' => 'Россия','region' => 'республика Удмуртия','city' => 'Ижевск','lat' => '56.8618601','lng' => '53.2324285'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Ivanteyevka','country' => 'Россия','region' => 'Московская область','city' => 'Ивантеевка','lat' => '55.975927','lng' => '37.9195199'),
        array('country_en' => 'Russia','region_en' => 'Ivanovo','city_en' => 'Ivanovo','country' => 'Россия','region' => 'Ивановская область','city' => 'Иваново','lat' => '57.0050671','lng' => '40.9766453'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Ishimbay','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Ишимбай','lat' => '53.4263581','lng' => '56.050767'),
        array('country_en' => 'Russia','region_en' => 'Vladimir','city_en' => 'Gus\'-Khrustal\'nyy','country' => 'Россия','region' => 'Владимирская область','city' => 'Гусь-Хрустальный','lat' => '55.6062836','lng' => '40.6563727'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Gukovo','country' => 'Россия','region' => 'Ростовская область','city' => 'Гуково','lat' => '48.0513115','lng' => '39.9377047'),
        array('country_en' => 'Russia','region_en' => 'Belgorod','city_en' => 'Gubkin','country' => 'Россия','region' => 'Белгородская область','city' => 'Губкин','lat' => '51.2824173','lng' => '37.543495'),
        array('country_en' => 'Russia','region_en' => 'Chechnya','city_en' => 'Groznyy','country' => 'Россия','region' => 'Чеченская Республика','city' => 'Грозный','lat' => '43.3168796','lng' => '45.6814856'),
        array('country_en' => 'Russia','region_en' => 'Udmurtiya','city_en' => 'Glazov','country' => 'Россия','region' => 'республика Удмуртия','city' => 'Глазов','lat' => '58.1368837','lng' => '52.6548341'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Georgiyevsk','country' => 'Россия','region' => 'Ставропольский край','city' => 'Георгиевск','lat' => '44.1497667','lng' => '43.4577689'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Gelendzhik','country' => 'Россия','region' => 'Краснодарский край','city' => 'Геленджик','lat' => '44.5918615','lng' => '38.0241663'),
        array('country_en' => 'Russia','region_en' => 'Leningrad','city_en' => 'Gatchina','country' => 'Россия','region' => 'Ленинградская область','city' => 'Гатчина','lat' => '59.5624627','lng' => '30.1064659'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Fryazino','country' => 'Россия','region' => 'Московская область','city' => 'Фрязино','lat' => '55.9602597','lng' => '38.0441437'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Fryazevo','country' => 'Россия','region' => 'Московская область','city' => 'Фрязево','lat' => '55.731249','lng' => '38.4679948'),
        array('country_en' => 'Russia','region_en' => 'Saratov','city_en' => 'Engel\'s','country' => 'Россия','region' => 'Саратовская область','city' => 'Энгельс','lat' => '51.4753297','lng' => '46.1136773'),
        array('country_en' => 'Russia','region_en' => 'Kalmykiya','city_en' => 'Elista','country' => 'Россия','region' => 'Республика Калмыкия','city' => 'Элиста','lat' => '46.3154883','lng' => '44.2794012'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Elektrostal\'','country' => 'Россия','region' => 'Московская область','city' => 'Электросталь','lat' => '55.7835532','lng' => '38.4551611'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Dzerzhinsk','country' => 'Россия','region' => 'Нижегородская область','city' => 'Дзержинск','lat' => '56.2440992','lng' => '43.4351804'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Dubna','country' => 'Россия','region' => 'Московская область','city' => 'Дубна','lat' => '56.7320202','lng' => '37.1668974'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Donetsk','country' => 'Россия','region' => 'Ростовская область','city' => 'Донецк','lat' => '48.3321569','lng' => '39.9653797'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Domodedovo','country' => 'Россия','region' => 'Московская область','city' => 'Домодедово','lat' => '55.4430234','lng' => '37.747817'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Dolgoprudnyy','country' => 'Россия','region' => 'Московская область','city' => 'Долгопрудный','lat' => '55.947064','lng' => '37.4992755'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Dmitrov','country' => 'Россия','region' => 'Московская область','city' => 'Дмитров','lat' => '56.3427702','lng' => '37.5288416'),
        array('country_en' => 'Russia','region_en' => 'Ulyanovsk','city_en' => 'Dimitrovgrad','country' => 'Россия','region' => 'Ульяновская область','city' => 'Димитровград','lat' => '54.2269792','lng' => '49.5684572'),
        array('country_en' => 'Russia','region_en' => 'Dagestan','city_en' => 'Derbent','country' => 'Россия','region' => 'Республика Дагестан','city' => 'Дербент','lat' => '42.0674251','lng' => '48.2890907'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Chusovoy','country' => 'Россия','region' => 'Пермский край','city' => 'Чусовой','lat' => '58.2817913','lng' => '57.8192543'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Chistopol\'','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Чистополь','lat' => '55.3617503','lng' => '50.6338908'),
        array('country_en' => 'Russia','region_en' => 'Karachayevo-Cherkesiya','city_en' => 'Cherkessk','country' => 'Россия','region' => 'Карачаево-Черкесская Республика','city' => 'Черкесск','lat' => '44.2273974','lng' => '42.0591708'),
        array('country_en' => 'Russia','region_en' => 'Vologda','city_en' => 'Cherepovets','country' => 'Россия','region' => 'Вологодская область','city' => 'Череповец','lat' => '59.132333','lng' => '37.9091811'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Chekhov','country' => 'Россия','region' => 'Московская область','city' => 'Чехов','lat' => '55.1526207','lng' => '37.4604756'),
        array('country_en' => 'Russia','region_en' => 'Chuvashia','city_en' => 'Cheboksary','country' => 'Россия','region' => 'Чувашская Республика','city' => 'Чебоксары','lat' => '56.1167663','lng' => '47.262782'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Chaykovskiy','country' => 'Россия','region' => 'Пермский край','city' => 'Чайковский','lat' => '56.766116','lng' => '54.1276714'),
        array('country_en' => 'Russia','region_en' => 'Samara','city_en' => 'Chapayevsk','country' => 'Россия','region' => 'Самарская область','city' => 'Чапаевск','lat' => '52.9696663','lng' => '49.7067317'),
        array('country_en' => 'Russia','region_en' => 'Orenburg','city_en' => 'Buzuluk','country' => 'Россия','region' => 'Оренбургская область','city' => 'Бузулук','lat' => '52.7732825','lng' => '52.2613248'),
        array('country_en' => 'Russia','region_en' => 'Dagestan','city_en' => 'Buynaksk','country' => 'Россия','region' => 'Республика Дагестан','city' => 'Буйнакск','lat' => '42.8222753','lng' => '47.1165961'),
        array('country_en' => 'Russia','region_en' => 'Orenburg','city_en' => 'Buguruslan','country' => 'Россия','region' => 'Оренбургская область','city' => 'Бугуруслан','lat' => '53.6234055','lng' => '52.4332215'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Bugul\'ma','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Бугульма','lat' => '54.5220314','lng' => '52.8260805'),
        array('country_en' => 'Russia','region_en' => 'Stavropol\'skiy','city_en' => 'Budennovsk','country' => 'Россия','region' => 'Ставропольский край','city' => 'Буденновск','lat' => '44.7925204','lng' => '44.1536162'),
        array('country_en' => 'Russia','region_en' => 'Brjansk','city_en' => 'Bryansk','country' => 'Россия','region' => 'Брянская область','city' => 'Брянск','lat' => '53.2635306','lng' => '34.41611'),
        array('country_en' => 'Russia','region_en' => 'Novgorod','city_en' => 'Borovichi','country' => 'Россия','region' => 'Новгородская область','city' => 'Боровичи','lat' => '58.3925508','lng' => '33.9068256'),
        array('country_en' => 'Russia','region_en' => 'Voronezj','city_en' => 'Borisoglebsk','country' => 'Россия','region' => 'Воронежская область','city' => 'Борисоглебск','lat' => '51.3680942','lng' => '42.0825626'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Bor','country' => 'Россия','region' => 'Нижегородская область','city' => 'Бор','lat' => '56.3588296','lng' => '44.0766797'),
        array('country_en' => 'Russia','region_en' => 'Moscow','city_en' => 'Bibirevo','country' => 'Россия','region' => 'Тверская область','city' => 'Бибирево','lat' => '58.0329829','lng' => '36.9649978'),
        array('country_en' => 'Russia','region_en' => 'Perm','city_en' => 'Berezniki','country' => 'Россия','region' => 'Пермский край','city' => 'Березники','lat' => '59.4131827','lng' => '56.7849318'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Beloretsk','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Белорецк','lat' => '53.9673992','lng' => '58.4060639'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Belorechensk','country' => 'Россия','region' => 'Краснодарский край','city' => 'Белореченск','lat' => '44.7591972','lng' => '39.8817157'),
        array('country_en' => 'Russia','region_en' => 'Belgorod','city_en' => 'Belgorod','country' => 'Россия','region' => 'Белгородская область','city' => 'Белгород','lat' => '50.5997134','lng' => '36.5982621'),
        array('country_en' => 'Russia','region_en' => 'Bashkortostan','city_en' => 'Belebey','country' => 'Россия','region' => 'Республика Башкортостан','city' => 'Белебей','lat' => '54.1103461','lng' => '54.1046266'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Bataysk','country' => 'Россия','region' => 'Ростовская область','city' => 'Батайск','lat' => '47.139761','lng' => '39.7378477'),
        array('country_en' => 'Russia','region_en' => 'Saratov','city_en' => 'Balashov','country' => 'Россия','region' => 'Саратовская область','city' => 'Балашов','lat' => '51.543181','lng' => '43.1770959'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Balashikha','country' => 'Россия','region' => 'Московская область','city' => 'Балашиха','lat' => '55.7981904','lng' => '37.9679867'),
        array('country_en' => 'Russia','region_en' => 'Saratov','city_en' => 'Balakovo','country' => 'Россия','region' => 'Саратовская область','city' => 'Балаково','lat' => '52.0245587','lng' => '47.7806626'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Balakhna','country' => 'Россия','region' => 'Нижегородская область','city' => 'Балахна','lat' => '56.5017433','lng' => '43.5633715'),
        array('country_en' => 'Russia','region_en' => 'Rostov','city_en' => 'Azov','country' => 'Россия','region' => 'Ростовская область','city' => 'Азов','lat' => '47.0947446','lng' => '39.4136552'),
        array('country_en' => 'Russia','region_en' => 'Astrakhan','city_en' => 'Astrakhan\'','country' => 'Россия','region' => 'Астраханская область','city' => 'Астрахань','lat' => '46.3588045','lng' => '48.0599345'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Arzamas','country' => 'Россия','region' => 'Нижегородская область','city' => 'Арзамас','lat' => '55.3964609','lng' => '43.8299175'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Armavir','country' => 'Россия','region' => 'Краснодарский край','city' => 'Армавир','lat' => '44.9873603','lng' => '41.1111326'),
        array('country_en' => 'Russia','region_en' => 'Arkhangelskaya','city_en' => 'Arkhangel\'sk','country' => 'Россия','region' => 'Архангельская область','city' => 'Архангельск','lat' => '64.5472507','lng' => '40.5601553'),
        array('country_en' => 'Russia','region_en' => 'Murmansk','city_en' => 'Apatity','country' => 'Россия','region' => 'Мурманская область','city' => 'Апатиты','lat' => '67.5777881','lng' => '33.3904158'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Anapa','country' => 'Россия','region' => 'Краснодарский край','city' => 'Анапа','lat' => '44.8857008','lng' => '37.3199191'),
        array('country_en' => 'Russia','region_en' => 'Tatarstan','city_en' => 'Al\'met\'yevsk','country' => 'Россия','region' => 'Республика Татарстан','city' => 'Альметьевск','lat' => '54.8937128','lng' => '52.317293'),
        array('country_en' => 'Russia','region_en' => 'Tula','city_en' => 'Aleksin','country' => 'Россия','region' => 'Тульская область','city' => 'Алексин','lat' => '54.5072013','lng' => '37.0013226'),
        array('country_en' => 'Russia','region_en' => 'Vladimir','city_en' => 'Aleksandrov','country' => 'Россия','region' => 'Владимирская область','city' => 'Александров','lat' => '56.3947309','lng' => '38.712037'),
        array('country_en' => 'Russia','region_en' => 'Krasnodarskiy','city_en' => 'Adler','country' => 'Россия','region' => 'Краснодарский край','city' => 'Адлер','lat' => '43.4343234','lng' => '39.9339462'),
        array('country_en' => 'Russia','region_en' => 'Nizjnij Novgorod','city_en' => 'Pavlovo','country' => 'Россия','region' => 'Нижегородская область','city' => 'Павлово','lat' => '55.9545317','lng' => '43.0818506'),
        array('country_en' => 'Russia','region_en' => 'Altai Krai','city_en' => 'Zarinsk','country' => 'Россия','region' => 'Алтайский край','city' => 'Заринск','lat' => '53.7273796','lng' => '84.9265074'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Yurga','country' => 'Россия','region' => 'Кемеровская область','city' => 'Юрга','lat' => '55.7297643','lng' => '84.8944519'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Yekaterinburg','country' => 'Россия','region' => 'Свердловская область','city' => 'Екатеринбург','lat' => '56.8389261','lng' => '60.6057025'),
        array('country_en' => 'Russia','region_en' => 'Komi Republic','city_en' => 'Vorkuta','country' => 'Россия','region' => 'Республика Коми','city' => 'Воркута','lat' => '67.4968967','lng' => '64.0602175'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Verkhnyaya Pyshma','country' => 'Россия','region' => 'Свердловская область','city' => 'Верхняя Пышма','lat' => '56.9664827','lng' => '60.5864162'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Zelenogorsk','country' => 'Россия','region' => 'Красноярский край','city' => 'Зеленогорск','lat' => '56.1124','lng' => '94.5985'),
        array('country_en' => 'Russia','region_en' => 'Tjumen','city_en' => 'Tyumen','country' => 'Россия','region' => 'Тюменская область','city' => 'Тюмень','lat' => '57.1612975','lng' => '65.5250172'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Troitsk','country' => 'Россия','region' => 'Челябинская область','city' => 'Троицк','lat' => '54.0747574','lng' => '61.567051'),
        array('country_en' => 'Russia','region_en' => 'Tomsk','city_en' => 'Tomsk','country' => 'Россия','region' => 'Томская область','city' => 'Томск','lat' => '56.5010397','lng' => '84.9924506'),
        array('country_en' => 'Russia','region_en' => 'Tjumen','city_en' => 'Tobol\'sk','country' => 'Россия','region' => 'Тюменская область','city' => 'Тобольск','lat' => '58.200024','lng' => '68.2635228'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Talnakh','country' => 'Россия','region' => 'Красноярский край','city' => 'Талнах','lat' => '69.5','lng' => '88.4'),
        array('country_en' => 'Russia','region_en' => 'Khanty-Mansiyskiy Avtonomnyy Okrug','city_en' => 'Surgut','country' => 'Россия','region' => 'Ханты-Мансийский автономный округ','city' => 'Сургут','lat' => '61.2559503','lng' => '73.3845471'),
        array('country_en' => 'Russia','region_en' => 'Kurgan','city_en' => 'Shadrinsk','country' => 'Россия','region' => 'Курганская область','city' => 'Шадринск','lat' => '56.0882558','lng' => '63.634265'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Serov','country' => 'Россия','region' => 'Свердловская область','city' => 'Серов','lat' => '59.6104645','lng' => '60.6177431'),
        array('country_en' => 'Russia','region_en' => 'Altai Krai','city_en' => 'Rubtsovsk','country' => 'Россия','region' => 'Алтайский край','city' => 'Рубцовск','lat' => '51.5140399','lng' => '81.2317683'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Prokop\'yevsk','country' => 'Россия','region' => 'Кемеровская область','city' => 'Прокопьевск','lat' => '53.888753','lng' => '86.7591829'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Polevskoy','country' => 'Россия','region' => 'Свердловская область','city' => 'Полевской','lat' => '56.4824818','lng' => '60.2446478'),
        array('country_en' => 'Russia','region_en' => 'Omsk','city_en' => 'Omsk','country' => 'Россия','region' => 'Омская область','city' => 'Омск','lat' => '54.9884804','lng' => '73.3242362'),
        array('country_en' => 'Russia','region_en' => 'Khanty-Mansiyskiy Avtonomnyy Okrug','city_en' => 'Nyagan','country' => 'Россия','region' => 'Ханты-Мансийский автономный округ','city' => 'Нягань','lat' => '62.129277','lng' => '65.3745138'),
        array('country_en' => 'Russia','region_en' => 'Yamalo-Nenetskiy Avtonomnyy Okrug','city_en' => 'Noyabrsk','country' => 'Россия','region' => 'Ямало-Ненецкий автономный округ','city' => 'Ноябрьск','lat' => '63.1841959','lng' => '75.4477605'),
        array('country_en' => 'Russia','region_en' => 'Yamalo-Nenetskiy Avtonomnyy Okrug','city_en' => 'Novyy Urengoy','country' => 'Россия','region' => 'Ямало-Ненецкий автономный округ','city' => 'Новый Уренгой','lat' => '66.0956864','lng' => '76.6563522'),
        array('country_en' => 'Russia','region_en' => 'Novosibirsk','city_en' => 'Novosibirsk','country' => 'Россия','region' => 'Новосибирская область','city' => 'Новосибирск','lat' => '55.0083526','lng' => '82.9357327'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Novokuznetsk','country' => 'Россия','region' => 'Кемеровская область','city' => 'Новокузнецк','lat' => '53.7595935','lng' => '87.1215705'),
        array('country_en' => 'Russia','region_en' => 'Altai Krai','city_en' => 'Novoaltaysk','country' => 'Россия','region' => 'Алтайский край','city' => 'Новоалтайск','lat' => '53.4415721','lng' => '83.9208351'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Norilsk','country' => 'Россия','region' => 'Красноярский край','city' => 'Норильск','lat' => '69.35579','lng' => '88.1892938'),
        array('country_en' => 'Russia','region_en' => 'Khanty-Mansiyskiy Avtonomnyy Okrug','city_en' => 'Nizhnevartovsk','country' => 'Россия','region' => 'Ханты-Мансийский автономный округ','city' => 'Нижневартовск','lat' => '60.9431185','lng' => '76.5433724'),
        array('country_en' => 'Russia','region_en' => 'Khanty-Mansiyskiy Avtonomnyy Okrug','city_en' => 'Nefteyugansk','country' => 'Россия','region' => 'Ханты-Мансийский автономный округ','city' => 'Нефтеюганск','lat' => '61.0980641','lng' => '72.5816466'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Nazarovo','country' => 'Россия','region' => 'Красноярский край','city' => 'Назарово','lat' => '56.0131955','lng' => '90.402565'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Minusinsk','country' => 'Россия','region' => 'Красноярский край','city' => 'Минусинск','lat' => '53.6978211','lng' => '91.6963172'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Miass','country' => 'Россия','region' => 'Челябинская область','city' => 'Миасс','lat' => '55.0506795','lng' => '60.1034961'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Mezhdurechensk','country' => 'Россия','region' => 'Кемеровская область','city' => 'Междуреченск','lat' => '53.6836301','lng' => '88.0813924'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Lesosibirsk','country' => 'Россия','region' => 'Красноярский край','city' => 'Лесосибирск','lat' => '58.2276178','lng' => '92.4960319'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Leninsk-Kuznetsky','country' => 'Россия','region' => 'Кемеровская область','city' => 'Ленинск-Кузнецкий','lat' => '54.6699128','lng' => '86.1734538'),
        array('country_en' => 'Russia','region_en' => 'Tyva','city_en' => 'Kyzyl','country' => 'Россия','region' => 'Республика Тува','city' => 'Кызыл','lat' => '51.7150832','lng' => '94.4574804'),
        array('country_en' => 'Russia','region_en' => 'Kurgan','city_en' => 'Kurgan','country' => 'Россия','region' => 'Курганская область','city' => 'Курган','lat' => '55.4649113','lng' => '65.3053512'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Krasnoyarsk','country' => 'Россия','region' => 'Красноярский край','city' => 'Красноярск','lat' => '56.0152834','lng' => '92.8932476'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Krasnotur\'insk','country' => 'Россия','region' => 'Свердловская область','city' => 'Краснотурьинск','lat' => '59.7650618','lng' => '60.2158834'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Kopeysk','country' => 'Россия','region' => 'Челябинская область','city' => 'Копейск','lat' => '55.1339695','lng' => '61.6457637'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Kiselevsk','country' => 'Россия','region' => 'Кемеровская область','city' => 'Киселевск','lat' => '54.0055243','lng' => '86.649758'),
        array('country_en' => 'Russia','region_en' => 'Khanty-Mansiyskiy Avtonomnyy Okrug','city_en' => 'Khanty-Mansiysk','country' => 'Россия','region' => 'Ханты-Мансийский автономный округ','city' => 'Ханты-Мансийск','lat' => '61.0090919','lng' => '69.0374596'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Kemerovo','country' => 'Россия','region' => 'Кемеровская область','city' => 'Кемерово','lat' => '55.3450231','lng' => '86.0623044'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Kansk','country' => 'Россия','region' => 'Красноярский край','city' => 'Канск','lat' => '56.2168141','lng' => '95.7198146'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Kamensk-Ural\'skiy','country' => 'Россия','region' => 'Свердловская область','city' => 'Каменск-Уральский','lat' => '56.4253389','lng' => '61.9222979'),
        array('country_en' => 'Russia','region_en' => 'Novosibirsk','city_en' => 'Iskitim','country' => 'Россия','region' => 'Новосибирская область','city' => 'Искитим','lat' => '54.6167986','lng' => '83.3055678'),
        array('country_en' => 'Russia','region_en' => 'Tjumen','city_en' => 'Ishim','country' => 'Россия','region' => 'Тюменская область','city' => 'Ишим','lat' => '56.1146308','lng' => '69.4771245'),
        array('country_en' => 'Russia','region_en' => 'Altai Republic','city_en' => 'Gorno-Altaysk','country' => 'Россия','region' => 'Республика Алтай','city' => 'Горно-Алтайск','lat' => '51.942186','lng' => '85.9719355'),
        array('country_en' => 'Russia','region_en' => 'Khakasiya','city_en' => 'Chernogorsk','country' => 'Россия','region' => 'Республика Хакасия','city' => 'Черногорск','lat' => '53.8247092','lng' => '91.322872'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Chelyabinsk','country' => 'Россия','region' => 'Челябинская область','city' => 'Челябинск','lat' => '55.1644419','lng' => '61.4368431'),
        array('country_en' => 'Russia','region_en' => 'Altai Krai','city_en' => 'Biysk','country' => 'Россия','region' => 'Алтайский край','city' => 'Бийск','lat' => '52.5072747','lng' => '85.1472004'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Berezovskiy','country' => 'Россия','region' => 'Кемеровская область','city' => 'Березовский','lat' => '55.571186','lng' => '86.1955771'),
        array('country_en' => 'Russia','region_en' => 'Novosibirsk','city_en' => 'Berdsk','country' => 'Россия','region' => 'Новосибирская область','city' => 'Бердск','lat' => '54.7750638','lng' => '83.0800316'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Belovo','country' => 'Россия','region' => 'Кемеровская область','city' => 'Белово','lat' => '54.4102969','lng' => '86.2936947'),
        array('country_en' => 'Russia','region_en' => 'Altai Krai','city_en' => 'Barnaul','country' => 'Россия','region' => 'Алтайский край','city' => 'Барнаул','lat' => '53.3547792','lng' => '83.7697832'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Asbest','country' => 'Россия','region' => 'Свердловская область','city' => 'Асбест','lat' => '57.0021465','lng' => '61.4582177'),
        array('country_en' => 'Russia','region_en' => 'Kemerovo','city_en' => 'Anzhero-Sudzhensk','country' => 'Россия','region' => 'Кемеровская область','city' => 'Анжеро-Судженск','lat' => '56.0838416','lng' => '86.0251017'),
        array('country_en' => 'Russia','region_en' => 'Krasnoyarskiy','city_en' => 'Achinsk','country' => 'Россия','region' => 'Красноярский край','city' => 'Ачинск','lat' => '56.2360841','lng' => '90.4903153'),
        array('country_en' => 'Russia','region_en' => 'Khakasiya','city_en' => 'Abakan','country' => 'Россия','region' => 'Республика Хакасия','city' => 'Абакан','lat' => '53.7175644','lng' => '91.4293172'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Snezhinsk','country' => 'Россия','region' => 'Челябинская область','city' => 'Снежинск','lat' => '56.0571732','lng' => '60.7543988'),
        array('country_en' => 'Russia','region_en' => 'Chelyabinsk','city_en' => 'Ozersk','country' => 'Россия','region' => 'Челябинская область','city' => 'Озёрск','lat' => '55.71381','lng' => '60.7009592'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Novoural\'sk','country' => 'Россия','region' => 'Свердловская область','city' => 'Новоуральск','lat' => '57.2575239','lng' => '60.0834488'),
        array('country_en' => 'Russia','region_en' => 'Tomsk','city_en' => 'Seversk','country' => 'Россия','region' => 'Томская область','city' => 'Северск','lat' => '56.6192692','lng' => '84.8816834'),
        array('country_en' => 'Russia','region_en' => 'Sakha','city_en' => 'Yakutsk','country' => 'Россия','region' => 'Республика Саха (Якутия)','city' => 'Якутск','lat' => '62.0354523','lng' => '129.6754745'),
        array('country_en' => 'Russia','region_en' => 'Primorskiy','city_en' => 'Vladivostok','country' => 'Россия','region' => 'Приморский край','city' => 'Владивосток','lat' => '43.1737387','lng' => '132.0064506'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Ust\'-Ilimsk','country' => 'Россия','region' => 'Иркутская область','city' => 'Усть-Илимск','lat' => '57.9845406','lng' => '102.7395955'),
        array('country_en' => 'Russia','region_en' => 'Primorskiy','city_en' => 'Ussuriysk','country' => 'Россия','region' => 'Приморский край','city' => 'Уссурийск','lat' => '43.8023134','lng' => '131.963089'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Usol\'ye-Sibirskoye','country' => 'Россия','region' => 'Иркутская область','city' => 'Усолье-Сибирское','lat' => '52.7664236','lng' => '103.6381712'),
        array('country_en' => 'Russia','region_en' => 'Respublika Buryatiya','city_en' => 'Ulan-Ude','country' => 'Россия','region' => 'Республика Бурятия','city' => 'Улан-Удэ','lat' => '51.8238785','lng' => '107.607338'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Tulun','country' => 'Россия','region' => 'Иркутская область','city' => 'Тулун','lat' => '54.5699077','lng' => '100.5817565'),
        array('country_en' => 'Russia','region_en' => 'Amur','city_en' => 'Svobodnyy','country' => 'Россия','region' => 'Амурская область','city' => 'Свободный','lat' => '51.3768658','lng' => '128.1347222'),
        array('country_en' => 'Russia','region_en' => 'Sakha','city_en' => 'Neryungri','country' => 'Россия','region' => 'Республика Саха (Якутия)','city' => 'Нерюнгри','lat' => '56.6614269','lng' => '124.7058164'),
        array('country_en' => 'Russia','region_en' => 'Primorskiy','city_en' => 'Nakhodka','country' => 'Россия','region' => 'Приморский край','city' => 'Находка','lat' => '42.8222753','lng' => '132.8834039'),
        array('country_en' => 'Russia','region_en' => 'Transbaikal Territory','city_en' => 'Krasnokamensk','country' => 'Россия','region' => 'Забайкальский край','city' => 'Краснокаменск','lat' => '50.0966137','lng' => '118.0361308'),
        array('country_en' => 'Russia','region_en' => 'Khabarovsk Krai','city_en' => 'Komsomolsk-on-Amur','country' => 'Россия','region' => 'Хабаровский край','city' => 'Комсомольск-на-Амуре','lat' => '50.5670331','lng' => '136.9658947'),
        array('country_en' => 'Russia','region_en' => 'Khabarovsk Krai','city_en' => 'Khabarovsk','country' => 'Россия','region' => 'Хабаровский край','city' => 'Хабаровск','lat' => '48.5027313','lng' => '135.0662599'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Irkutsk','country' => 'Россия','region' => 'Иркутская область','city' => 'Иркутск','lat' => '52.2869741','lng' => '104.3050183'),
        array('country_en' => 'Russia','region_en' => 'Transbaikal Territory','city_en' => 'Chita','country' => 'Россия','region' => 'Забайкальский край','city' => 'Чита','lat' => '52.0515032','lng' => '113.4711906'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Cheremkhovo','country' => 'Россия','region' => 'Иркутская область','city' => 'Черемхово','lat' => '53.1400556','lng' => '103.0939762'),
        array('country_en' => 'Russia','region_en' => 'Amur','city_en' => 'Blagoveshchensk','country' => 'Россия','region' => 'Амурская область','city' => 'Благовещенск','lat' => '50.2727763','lng' => '127.5404017'),
        array('country_en' => 'Russia','region_en' => 'Jewish Autonomous Oblast','city_en' => 'Birobidzhan','country' => 'Россия','region' => 'Еврейская автономная область','city' => 'Биробиджан','lat' => '48.7803574','lng' => '132.9130744'),
        array('country_en' => 'Russia','region_en' => 'Amur','city_en' => 'Belogorsk','country' => 'Россия','region' => 'Амурская область','city' => 'Белогорск','lat' => '50.919895','lng' => '128.4833835'),
        array('country_en' => 'Russia','region_en' => 'Primorskiy','city_en' => 'Artem','country' => 'Россия','region' => 'Приморский край','city' => 'Артем','lat' => '43.3696608','lng' => '132.1724749'),
        array('country_en' => 'Russia','region_en' => 'Primorskiy','city_en' => 'Arsen\'yev','country' => 'Россия','region' => 'Приморский край','city' => 'Арсеньев','lat' => '44.1580429','lng' => '133.2645475'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Angarsk','country' => 'Россия','region' => 'Иркутская область','city' => 'Ангарск','lat' => '52.5155702','lng' => '103.91716'),
        array('country_en' => 'Russia','region_en' => 'Irkutsk','city_en' => 'Bratsk','country' => 'Россия','region' => 'Иркутская область','city' => 'Братск','lat' => '56.1737661','lng' => '101.6038976'),
        array('country_en' => 'Russia','region_en' => 'Sakhalin','city_en' => 'Yuzhno-Sakhalinsk','country' => 'Россия','region' => 'Сахалинская область','city' => 'Южно-Сахалинск','lat' => '46.9641127','lng' => '142.7347556'),
        array('country_en' => 'Russia','region_en' => 'Kamtsjatka','city_en' => 'Petropavlovsk-Kamchatsky','country' => 'Россия','region' => 'Камчатский край','city' => 'Петропавловск-Камчатский','lat' => '53.0409109','lng' => '158.6777259'),
        array('country_en' => 'Russia','region_en' => 'Magadan','city_en' => 'Magadan','country' => 'Россия','region' => 'Магаданская область','city' => 'Магадан','lat' => '59.5611525','lng' => '150.8301413'),
        array('country_en' => 'Russia','region_en' => 'Khanty-Mansiyskiy Avtonomnyy Okrug','city_en' => 'Kogalym','country' => 'Россия','region' => 'Ханты-Мансийский автономный округ','city' => 'Когалым','lat' => '62.2665501','lng' => '74.5446849'),
        array('country_en' => 'Russia','region_en' => 'Sverdlovsk','city_en' => 'Lesnoy','country' => 'Россия','region' => 'Свердловская область','city' => 'Лесной','lat' => '56.750043','lng' => '60.4348384'),
        array('country_en' => 'Russia','region_en' => 'MO','city_en' => 'Vostochnoe Degunino','country' => 'Россия','region' => 'город Москва','city' => 'район Восточное Дегунино','lat' => '55.8840082','lng' => '37.5573562')
    );
    public function run()
    {
        foreach ($this->reg as $regArr) {
            $region = new Region();
            $region->country_en = $regArr['country_en'];
            $region->region_en = $regArr['region_en'];
            $region->city_en = $regArr['city_en'];
            $region->country = $regArr['country'];
            $region->region = $regArr['region'];
            $region->city = $regArr['city'];
            $region->lat = $regArr['lat'];
            $region->lang = $regArr['lng'];
            $region->save();
        }
    }
}

